---
title: "strings_and_factors"
author: "Rosie Kwon"
date: "2025-10-14"
output: github_document
---

Load key packages.
```{r}
library(rvest)
library(tidyverse)
library(stringr)
```

```{r}
library(p8105.datasets)
```

## Strings and regex

```{r}
string_vec = c("my", "name", "is", "rosie")

str_detect(string_vec, "rosie")
```


```{r}
str_replace(string_vec, "rosie", "Rosie")
```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think")
str_detect(string_vec, "i think$")

str_remove(string_vec, "i think$")
```

designate a list of characters that will count as a match.

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

The character `.` matches anything.

```{r}
string_vec = c(
  'Its 7:11 in the evening', #TRUE
  'want to go to 7-11?', #TRUE
  'my flight is AA711', #FALSE
  'NetBios: scanning ip 203.167.114.66' #TRUE
  )

str_detect(string_vec, "7.11")
```

special characters : `[` and `]`, `(` and `)`, and `.`
(To search for those,  use a string `\`)

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Thoughts on factors

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
```

```{r}
as.numeric(vec_sex)
vec_sex = fct_relevel(vec_sex, "male")
vec_sex
```

#NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"


table_marj = 
  read_html(nsduh_url) |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

tidy data 
```{r}
data_marj = 
  table_marj |> 
  select(-contains("P Value")) |> 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |> 
  mutate(
    year = str_replace(year, "\\)",""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

Visualize

```{r}
data_marj |> 
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Restaurant inspections

```{r}
data("rest_inspec")

rest_inspec = 
    rest_inspec |> 
    rename(borough = boro)
```

remove inspections with scores other than A, B, or C
```{r}
rest_inspec = 
  rest_inspec |> 
  filter(grade %in% c("A","B","C"), borough != "Missing") |> 
  mutate(borough = str_to_title(borough))
```

```{r}
rest_inspec |> 
  group_by(borough, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(names_from = grade, values_from = n)
```

